### ISSUE TITLE
(optional)animation for icon inside a app

### ISSUE THREAD

**Issue by NSTAdventure** [trynoice/android-app#753] opened 2021-08-13 07:44 UTC
### Is your feature request related to a problem? Please describe.
It would be boring if those nice icon doesn't have animation

### Describe the solution you'd like

Add animation on icon when sound played (also add toggle on setting which mean users can turn this feature on off)

**Comment by ashutoshgngwr** [comment] 2021-08-13 09:34
I will repeat myself. The purpose of Noice is to provide constant background noise while you do something else (besides staring at its UI). Thus, your point about things being boring without animations is invalid. Surely animations add a visual flair, but the needed development effort is quite significant when compared to the overall added value.

A brief consideration of available options makes it abundantly clear.

- Binary animations (GIF): Simpler to make but have large size on disk, and thus large APKs.
- SVG animations (path morphing): Small in size but even the [simplest animations are tricky to create](https://gist.github.com/ozgurg/0ff8e1e315b1cb5c385bda1c25da80e6)

**Comment by NSTAdventure** [comment] 2021-08-13 14:52
Yeah maybe like that tho imo it could be nice if those icon have some kind of animation :( 

#it'sMeMario

**Comment by ashutoshgngwr** [comment] 2021-08-13 16:21
The issue is open. If someone else wants to do it, it's up for grabs.

**Comment by NSTAdventure** [comment] 2021-08-25 04:32
> The issue is open. If someone else wants to do it, it's up for grabs.

Bruh 🗿🗿🗿🗿🗿

Why don't you just add that feature?

**Comment by timacosta** [comment] 2021-09-24 23:23
@ashutoshgngwr I would take a look if that's ok. Surely as you mentioned the purpose of Noice is to provide background sounds and therefore UI is kind of secondary (even though it has an nice one!) at least what animations refer to. Even though, I would like to take a look and assign the issue. Thx

**Comment by ashutoshgngwr** [comment] 2021-09-25 02:21
@timacosta yeah that'd be great!

**Comment by timacosta** [comment] 2021-11-26 16:23
@ashutoshgngwr I actually wanted to take some actions on this task during this week :) so if it's still wanted or required jut re-open it.

**Comment by ashutoshgngwr** [comment] 2021-11-27 06:11
@timacosta Okay!

**Comment by NSTAdventure** [comment] 2021-11-27 06:37
Yay! 😍😍😍😍

Thanks  for reopen my issues 🙏😊

Pada Sabtu, 27 November 2021, Ashutosh Gangwar ***@***.***>
menulis:

**Comment by ashutoshgngwr** [comment] 2022-07-09 07:02
I am closing this. I don't want to work on it, and there's barely any interest in this issue. Thanks for your suggestion, @NSTAdventure.

**Closed by ashutoshgngwr** 2022-07-09 07:02 UTC
Labels: enhancement

**Comment by NSTAdventure** [comment] 2022-07-09 07:08
> I am closing this. I don't want to work on it, and there's barely any interest in this issue. Thanks for your suggestion, @NSTAdventure.

i see is ok thanks for consideration 🙏😊
