### ISSUE TITLE
Saved preset is displayed as "Unsaved Preset" when pressing the stop button (intermittently occuring...)

### ISSUE THREAD

**Issue by SebastJava** [trynoice/android-app#1155] opened 2023-12-19 15:58 UTC
### Description

I play one of my saved presets. While this preset is playing, I just take a look at its composition by scrolling up and down through the library. I don't change anything, I am just looking at all the individual sound sources mixed in... Then I press the "stop" button and then the name displayed at the bottom of the screen is: "Unsaved Preset". This leaves me in a somewhat doubtful state: did I save my last tweaks or not? But yes, it was saved and there were no further tweaks, I tested this many times. Unfortunately, it isn't easy to reproduce, it only occurs intermittently !

### To Reproduce

1. Go to Presets and select one of yours...
2. Go to the library, and take some time to scroll up and down, just to take a look at this complex mix...
3. Press the "Stop" button at the bottom of your Android phone screen...
4. See? Your preset is now named as "Unsaved Preset" !

### Note

This bug only occurs once in a while. Maybe the key to trigger this bug is just... TIME !? I mean, just keep looking at the library for 5 minutes while listening to your custom preset, and then press the "Stop" button... :)

### Screenshots

![Screenshot_20231219-104147-LR](https://github.com/trynoice/android-app/assets/31940713/5511caf7-523f-4984-b7f3-876a094bcbde)

### Others

- Device: Moto G Pure
- Android Version: 12
- App Version: 2.5.4
- Downloaded From: Google Play

**Comment by ashutoshgngwr** [comment] 2023-12-19 16:09
Thanks for reporting this! iirc, it came up during the implementation, and I had been lazy about it. Nonetheless, I try to fix this as soon as possible.

**Comment by SebastJava** [comment] 2023-12-19 16:16
Thanks for this quick reply! I was currently trying to investigate what causes this bug to occur, exactly. Trying to find the exact steps to reproduce... Because this is that kind of mysterious bug that I can talk about, but I am not able to consistently reproduce it every time...

So, my question is: do you have a clear idea of the "steps to reproduce"? Or should I keep trying to find the exact combination of steps to reproduce this bug?

**Comment by ashutoshgngwr** [comment] 2023-12-19 16:26
@SebastJava Thank you for taking the time to investigate it. I don't remember exactly. There may have been several refactors since then. Perhaps it is best not to rely on my vague memory. If I were starting afresh, I'd start here:

https://github.com/trynoice/android-app/blob/262724df8deaa2f15f2a95b04300a9a3c07a55ae/app/src/main/java/com/github/ashutoshgngwr/noice/engine/SoundPlayerManager.kt#L275-L280

Most likely, it is broken. You can also look at `SoundPlaybackService`, where it is called to update a `StateFlow` on which the UI elements rely.

**Comment by ashutoshgngwr** [comment] 2023-12-19 18:00
@SebastJava I tried reproducing it myself! I think what happens is when you play a preset, not all sounds will be in the `PLAYING` state at the same time. A few of them might be in the `BUFFERING` state. When you hit stop, the sounds in the `PLAYING` state enter the `STOPPING` state, while the sounds in the `BUFFERING` state directly enter the `STOPPED` state. This is important because `SoundPlayerManager#getCurrentPreset` and `SoundPlaybackService` rely on sound states to find the active preset name, and sounds in `STOPPED` won't be part of the active preset. I hope this makes sense! Can you verify this?

To reproduce it, you need to hit stop before all sounds enter the `PLAYING` state. You can monitor sound states in log messages with the `SoundPlayerManager` tag.

**Comment by ashutoshgngwr** [comment] 2023-12-19 18:06
@SebastJava It should be easy to reproduce on a slow network since not all sounds from a preset will be able to buffer adequately to start concurrently.

**Comment by SebastJava** [comment] 2023-12-19 19:27
@ashutoshgngwr I am not really a programmer, but I am willing to learn... Maybe, one day, I will finally find the time, and a quiet environment, and peace of mind, so I can dive into these things more seriously.

I am currently writing this reply on my computer, with the latest Linux Mint Cinnamon OS. But here I am talking about your Noice app on my Moto G Pure cellular phone, with Android 12.

> [...] I hope this makes sense!

Yes, I approximately understand your reasoning and it makes sense. 

> To reproduce it, you need to hit stop before all sounds enter the `PLAYING` state. You can monitor sound states in log messages with the `SoundPlayerManager` tag. Can you verify this?

If I understand you correctly, your are saying this bug would only occur when I quickly press "stop", so there are still sounds in the `BUFFERING` state... But, from my various empirical tests, I get the feeling it just the opposite. This little bug only occurs when I press "stop" after some time, like after 2 minutes or so. I never get this bug if I just play my preset for 10 seconds and then stop.

And... what makes it even weirder is it seems I only get this bug with my custom presets.
This one: https://trynoice.com/preset?v=1&n=Cascades&s=%7B%22brownian_noise%22%3A1.0%2C%22pink_noise%22%3A0.8%2C%22water_stream%22%3A1.0%2C%22white_noise%22%3A0.4%2C%22wolves%22%3A0.5%7D

**Comment by SebastJava** [comment] 2023-12-19 19:33
> You can monitor sound states in log messages with the `SoundPlayerManager` tag. Can you verify this?

@ashutoshgngwr 

Sorry, I have trouble understanding this. I don't know how to find any log messages on my Moto G Pure Android 12 phone. Help please!

**Comment by SebastJava** [comment] 2023-12-19 19:39
Also, I believe my internet connection isn't so slow. I only use this nice Noice when at home. So, I have my own WiFi connection here. And I am the only user on it and thus I am pretty sure I always get the same steady ▲15 Mbit/s || ▼10 Mbit/s...

**Comment by SebastJava** [comment] 2023-12-20 03:05
@ashutoshgngwr All right ! I think I may have finally found the exact strange steps to reproduce...

 ### To reproduce
 
 1. Go to the Library.
 2. Choose at least one sound that repeats seamlessly, such as pink or white noise.
 3. Choose one sound that repeats with a random delay, such as wolves or thunder.
 4. Save your preset.
 5. Just listen and wait for at least 60 seconds, then press stop while no randomly delayed sound is playing, i.e. no wolf howls or thunder sounds.
 6. See? "Unsaved preset" is now displayed for 5 seconds, during the fade out...

Of course, I can't be sure, but I think I found it. I hope I am not wasting your time. The truth is I am a bit reluctant to dive into this big system logs investigation. It would probably be a fascinating adventure, but I currently have other concerns on my mind. I am busy with other things. This system logs investigation probably sounds easy for you, but the thing is I would have to start by installing the big SDK. This looks like a big adventure. Maybe later?

**Comment by ashutoshgngwr** [comment] 2023-12-20 08:16
Hey @SebastJava! Thank you for taking the time to dig deep and find the exact steps needed to reproduce this. I'll resolve it as soon as possible, perhaps over the weekend.

> I hope I am not wasting your time.

You didn't. Your input has been very helpful!

**Closed** 2023-12-31 16:20 UTC
Labels: bug, always-fresh

**Comment by ashutoshgngwr** [comment] 2023-12-31 16:41
@SebastJava I've added a fix to resolve this issue. Since it changes a few components' behaviours at the implementation's lowest level, I'm sceptical that it may cause unwanted side effects. Nevertheless, I've released a new version, 2.5.5, with this fix, and it should be available shortly on GitHub releases, F-Droid and Noice beta on the Google Play Store.

**Comment by SebastJava** [comment] 2023-12-31 16:45
Thanks !
